apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: mutate-deployment-policy
spec:
  steps:
  - name: step
    try:
    - apply:
        file: policy.yaml
    - assert:
        file: policy-assert.yaml