{
 "title": "Kubernetes / Kube-apiserver (advanced)",
 "description": "Advanced latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "tags": [ "Infrastructure" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"$job\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\", cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(apiserver_request_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notice",
   "type": "text",
   "description": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability (30d) > 99.000%",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "ErrorBudget (30d) > 99.000%",
   "type": "timeseries",
   "description": "How much error budget is left looking at our 0.990% availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * (apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"} - 0.990000)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Read Availability (30d)",
   "type": "stat",
   "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "timeseries",
   "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "graph",
   "description": "How many percent of read requests (LIST,GET) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\",code=~\"5..\", cluster=\"$cluster\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "timeseries",
   "description": "How many seconds is the 99th percentile for reading (LIST|GET) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile{verb=\"read\", cluster=\"$cluster\", resource != \"\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write Availability (30d)",
   "type": "stat",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "timeseries",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\"})",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "graph",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\",code=~\"5..\", cluster=\"$cluster\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "timeseries",
   "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_sli_duration_seconds:histogram_quantile{verb=\"write\", cluster=\"$cluster\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$__rate_interval])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}