{
 "title": "Karpenter Operational Dashboard (AWS)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", capacity_type=~\".+\"},node_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(karpenter_pods_state{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "nodepool",
    "label": "Nodepool",
    "query": {
     "query": "label_values(karpenter_nodepools_usage{cluster=\"$cluster\"},nodepool)"
    }
   },
   {
    "name": "workqueue_controller",
    "label": "Workqueue Controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_count{cluster=\"$cluster\", job=\"$job\"},controller)"
    }
   },
   {
    "name": "scheduling_controller",
    "label": "Scheduling Controller",
    "query": {
     "query": "label_values(karpenter_scheduler_queue_depth{cluster=\"$cluster\"},controller)"
    }
   },
   {
    "name": "nodeclaim",
    "label": "Nodeclaim",
    "query": {
     "query": "label_values(operator_status_condition_current_status_seconds{kind=\"NodeClaim\", cluster=\"$cluster\"},name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(karpenter_cloudprovider_instance_type_cpu_cores,job)"
    }
   },
   {
    "name": "capacity_type",
    "label": "Capacity Type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\"},capacity_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Resource Distribution Overview - nodepool \"$nodepool\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Nodes ($nodepool)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\",cluster=\"$cluster\"}) by (node_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods ($namespace)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{namespace=~\"$namespace\",nodepool=~\"$nodepool\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes  per AZ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{nodepool=~\"$nodepool\",resource_type=\"pods\",cluster=\"$cluster\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods  per AZ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"$nodepool\",cluster=\"$cluster\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes  per Nodepool",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{nodepool!=\"\",resource_type=\"pods\",cluster=\"$cluster\"}) by (nodepool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods  per Nodepool",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{phase=\"Running\",nodepool!=\"\",cluster=\"$cluster\"}) by (nodepool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Historical View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(sum(karpenter_nodes_allocatable{nodepool=~\"$nodepool\",cluster=\"$cluster\"}) by (node_name))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Pods Historical View ($namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count(karpenter_pods_state{namespace=~\"$namespace\",nodepool=~\"$nodepool\",cluster=\"$cluster\"})",
     "legendFormat": "pods"
    }
   ]
  },
  { "title": "Nodepool Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Nodepool Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "karpenter_nodepools_usage{resource_type=\"cpu\",cluster=\"$cluster\", nodepool!=\"\"} / karpenter_nodepools_limit{resource_type=\"cpu\",cluster=\"$cluster\", nodepool!=\"\"}",
     "legendFormat": "CPU Limit Utilization"
    },
    {
     "expr": "count by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"cpu\",cluster=\"$cluster\"}) # Selects a single resource type to get node count"
    },
    {
     "expr": "karpenter_nodepools_usage{nodepool!=\"\",resource_type=\"memory\",cluster=\"$cluster\"} / karpenter_nodepools_limit{nodepool!=\"\",resource_type=\"memory\",cluster=\"$cluster\"}",
     "legendFormat": "Memory Limit Utilization"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"cpu\",cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"memory\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{capacity_type=\"spot\",nodepool=~\"$nodepool\",cluster=\"$cluster\"}) or vector(0)) / count(karpenter_nodes_allocatable{nodepool=~\"$nodepool\",cluster=\"$cluster\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Nodes per Nodepool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count(sum(karpenter_nodes_allocatable{nodepool!=\"\",cluster=\"$cluster\"}) by (node_name,nodepool)) by (nodepool)",
     "legendFormat": "nodes:{{nodepool}}"
    },
    {
     "expr": "count(sum(karpenter_nodes_allocatable{cluster=\"\",nodepool!=\"\",cluster=\"$cluster\"}) by (node_name))",
     "legendFormat": "nodes total"
    }
   ]
  },
  {
   "title": "Pods per Nodepool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "count(karpenter_pods_state{namespace=~\"$namespace\",nodepool=\"$nodepool\",cluster=\"$cluster\"}) by (nodepool)",
     "legendFormat": "pods:{{nodepool}}"
    },
    {
     "expr": "count(karpenter_pods_state{namespace=~\"$namespace\",nodepool=\"$nodepool\",cluster=\"$cluster\"})",
     "legendFormat": "pods total"
    }
   ]
  },
  { "title": "Node Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",nodepool=~\"$nodepool\",cluster=\"$cluster\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",nodepool=~\"$nodepool\",cluster=\"$cluster\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",nodepool=~\"$nodepool\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",nodepool=~\"$nodepool\",cluster=\"$cluster\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",nodepool=~\"$nodepool\",cluster=\"$cluster\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",nodepool=~\"$nodepool\",cluster=\"$cluster\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",nodepool=~\"$nodepool\",cluster=\"$cluster\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",nodepool=~\"$nodepool\",cluster=\"$cluster\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds{cluster=\"$cluster\"}) - sum by (node)(node_boot_time_seconds{cluster=\"$cluster\"}),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Nodeclaim Ready and Uptime  - nodeclaim \"$nodeclaim\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Ready time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "operator_status_condition_current_status_seconds{kind=\"NodeClaim\", name=\"$nodeclaim\",status=\"True\", type=\"Launched\", cluster=\"$cluster\"} - ignoring(type,reason) operator_status_condition_current_status_seconds{kind=\"NodeClaim\", name=\"$nodeclaim\",status=\"True\", type=\"Ready\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "operator_status_condition_current_status_seconds{kind=\"NodeClaim\", name=\"$nodeclaim\",status=\"True\", type=\"Ready\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AWS API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "AWS API Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aws_sdk_go_request_duration_seconds_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le,exported_service,action))",
     "legendFormat": "{{exported_service}}:{{action}}"
    }
   ]
  },
  {
   "title": "AWS API Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "irate(aws_sdk_go_request_attempt_duration_seconds_count{code!=\"200\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{exported_service}}:{{action}}:{{code}}"
    }
   ]
  },
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Stuck NodeClaim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "operator_status_condition_transitions_total{group=\"karpenter.sh\",kind=\"NodeClaim\",reason=\"Launched\",status=\"True\",type=\"Launched\",cluster=\"$cluster\"} - ignoring(type,reason) operator_status_condition_transitions_total{group=\"karpenter.sh\",kind=\"NodeClaim\",reason=\"Ready\",status=\"True\",type=\"Ready\",cluster=\"$cluster\"}  ",
     "legendFormat": "Delta Launched - Ready"
    }
   ]
  },
  {
   "title": "Node Termination Latency - Nodepool \"$nodepool\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"0.99\",nodepool=~\"$nodepool\",cluster=\"$cluster\"})",
     "legendFormat": "P99 "
    }
   ]
  },
  {
   "title": "Pod Startup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"0.99\",cluster=\"$cluster\"})",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Pod phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state{cluster=\"$cluster\", nodepool=\"$nodepool\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Cloud Provider Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(karpenter_cloudprovider_errors_total{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{controller}}:{{error}}"
    }
   ]
  },
  { "title": "Controller Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Controller Reconciliation Latency - Workqueue Controller \"$workqueue_controller\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$workqueue_controller\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Workqueue Controller Reconciliation Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval])) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Simulation Latency - Scheduling Controller \"$scheduling_controller\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(karpenter_scheduler_scheduling_duration_seconds_bucket{controller=\"$workqueue_controller\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Controller Queue Depth - Scheduling Controller \"$scheduling_controller\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_scheduler_queue_depth{controller=\"$scheduling_controller\",cluster=\"$cluster\"})",
     "legendFormat": "queue depth"
    }
   ]
  }
 ]
}