{
 "title": "Kubernetes / Kube-apiserver (basic)",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "tags": [ "Infrastructure" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(apiserver_request_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "apiserver request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,verb)",
     "legendFormat": "{{instance}}: {{verb}} "
    }
   ]
  },
  {
   "title": "workqueue service time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p50"
    }
   ]
  },
  {
   "title": "apiserver request latency",
   "type": "timeseries",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p50 "
    }
   ]
  },
  {
   "title": "workqueue processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p50"
    }
   ]
  },
  {
   "title": "etcd request latency",
   "type": "timeseries",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\",job=\"$job\", instance=~\"$instance\"}[5m])) by (instance,le))",
     "legendFormat": "{{instance}}: p50"
    }
   ]
  }
 ]
}