{
 "title": "Node Exporter / Nodes",
 "tags": [ "infrastructure" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", nodename=~\"$instance\", cluster=\"$cluster\"}[5m])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$instance\", cluster=\"$cluster\"})\n) by (nodename)\n",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "Aggegated CPU load averages (average system load over a period of time)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_load1{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "1m load average"
    },
    {
     "expr": "sum(node_load5{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "5m load average"
    },
    {
     "expr": "sum(node_load15{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "15m load average"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Aggregated values of memory used, buffered, cached and free",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})\n-\n  sum(node_memory_MemFree_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})\n-\n  sum(node_memory_Buffers_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})\n-\n  sum(node_memory_Cached_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Overall memory consumption",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O - Read",
   "type": "timeseries",
   "description": "Disk read bytes per EC2 instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[5m])) by (nodename, device)",
     "legendFormat": "{{nodename}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[5m])) by (nodename, device)",
     "legendFormat": "{{nodename}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"node-exporter\", nodename=~\"$instance\", cluster=\"$cluster\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[5m])) by (nodename, device)",
     "legendFormat": "{{nodename}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "description": "Aggregated disk space available / used",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"node-exporter\", nodename=~\"$instance\", fstype!=\"\", cluster=\"$cluster\"}\n  -\n    node_filesystem_avail_bytes{job=\"node-exporter\", nodename=~\"$instance\", fstype!=\"\", cluster=\"$cluster\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"node-exporter\", nodename=~\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"node-exporter\", device!=\"lo\", nodename=~\"$instance\", cluster=\"$cluster\"}[5m])) by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\", device!=\"lo\", nodename=~\"$instance\", cluster=\"$cluster\"}[5m])) by (nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}