configs:
  cm:
    ui.bannerurl: "https://us-west-2.console.aws.amazon.com/eks/home?region=us-west-2#/clusters/workload-cluster1"

server:
  service:
   type: LoadBalancer
   annotations:
     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing