version: '3'

vars:
  NAMESPACE: argocd
  KUBE_VERSION: "1.32"

tasks:
  validate-helm-gitops-bridge:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: gitops/addons/charts/gitops-bridge
      RELEASE_NAME: cluster-addons    
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --values gitops/addons/default/addons/gitops-bridge/values.yaml \
          --values gitops/addons/environments/control-plane/addons/gitops-bridge/values.yaml \
          --values gitops/addons/tenants/auto1/default/addons/gitops-bridge/values.yaml \
          --values gitops/addons/tenants/auto1/environments/control-plane/addons/gitops-bridge/values.yaml \
          --include-crds --debug



  validate-helm-teams-backend:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: gitops/platform/charts/teams
      RELEASE_NAME: argoprojects-backend    
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --values gitops/platform/teams/backend/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/clusters/cluster5/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/clusters/cluster5/argoprojects/values.yaml \
          --include-crds --debug

  validate-helm-teams-frontend:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: gitops/platform/charts/teams
      RELEASE_NAME: argoprojects-frontend    
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --values gitops/platform/teams/frontend/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/clusters/cluster5/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/clusters/cluster5/argoprojects/values.yaml \
          --include-crds  --debug

  validate-helm-argocd-apps-frontend:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: argo/argocd-apps
      CHART_VERSION: 2.0.2
      RELEASE_NAME: argocd-apps-frontend
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --version {{.CHART_VERSION}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --values gitops/platform/teams/frontend/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/clusters/cluster5/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/frontend/tenants/auto1/clusters/cluster5/argoprojects/values.yaml \
          --include-crds  --debug     

  validate-helm-argocd-apps-backend:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: argo/argocd-apps
      CHART_VERSION: 2.0.2
      RELEASE_NAME: argocd-apps-backend
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --version {{.CHART_VERSION}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --values gitops/platform/teams/backend/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/clusters/cluster5/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/clusters/cluster5/argoprojects/values.yaml \
          --include-crds  --debug  

  validate-helm-appprojects-apps-backend:
    desc: Validate Helm template for gitops-bridge
    vars:
      CHART_PATH: argo/argocd-apps
      CHART_VERSION: 2.0.2
      RELEASE_NAME: argoprojects-backend
    cmds:
      - |
        helm template {{.RELEASE_NAME}} {{.CHART_PATH}} \
          --version {{.CHART_VERSION}} \
          --namespace {{.NAMESPACE}} \
          --kube-version {{.KUBE_VERSION}} \
          --set projects[0].sourceRepos[0]=https://github.com/aws-samples/fleet-management-on-amazon-eks-workshop.git \
          --values gitops/platform/teams/backend/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/environments/control-plane/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/defaults/argoprojects/values.yaml \
          --values gitops/platform/teams/backend/tenants/auto1/environments/control-plane/argoprojects/values.yaml \
          --include-crds --debug





  lint:
    desc: Lint the Helm chart
    cmds:
      - helm lint {{.CHART_PATH}}

  validate-all:
    desc: Run both template validation and linting
    deps: [validate-helm, lint]
