apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locust
rules:
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["create", "delete", "list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: locust
subjects:
- kind: ServiceAccount
  name: eks-loadtest-locust-worker
  namespace: default
roleRef:
  kind: ClusterRole
  name: locust
  apiGroup: rbac.authorization.k8s.io
