apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. Requiring use of known, approved
      registries helps reduce threat exposure by ensuring image pulls only come from them. This
      policy validates that container images originate from valide registries and NOT originate from the registry `k8s.gcr.io`. 
      Use of this policy requires customization to define your non allowable or allowable registries.
spec:
  validationFailureAction: audit
  background: true
  failurePolicy: Fail
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    skipBackgroundRequests: false
    validate:
      message: "Unknown image registry."
      pattern:
        {{- toYaml .Values.disallowedrepos | nindent 8 -}}
