clusters:

  cluster1:
    accountId: "908546734614"
    managementAccountId: "326864266654"
    tenant: "seb1"
    k8sVersion: "1.30"
    domainName: "cluster2.mydomain.com"
    gitops:
      addonsRepoRevision: "centralized-argocd"
      fleetRepoRevision: "centralized-argocd"
      platformRepoRevision: "centralized-argocd"
      workloadRepoRevision: "centralized-argocd"

  cluster5:
    accountId: "418272784034"
    managementAccountId: "382076407153"
    tenant: "seb1"
    k8sVersion: "1.30"
    domainName: "cluster5.rosa.allamand.com"
    gitops:
      addonsRepoRevision: "centralized-argocd"
      fleetRepoRevision: "centralized-argocd"
      platformRepoRevision: "centralized-argocd"
      workloadRepoRevision: "centralized-argocd"

  cluster6:
    accountId: "798082067117"
    managementAccountId: "382076407153"
    tenant: "seb1"
    k8sVersion: "1.30"
    domainName: "cluster6.rosa.allamand.com"
    gitops:
      addonsRepoRevision: "centralized-argocd"
      fleetRepoRevision: "centralized-argocd"
      platformRepoRevision: "centralized-argocd"
      workloadRepoRevision: "centralized-argocd"