# values for the addon
addons:
  aws_load_balancer_controller:
    enabled: true
  aws_ebs_csi_resources:
    enabled: true
  metrics_server:
    enabled: true
  karpenter:
    enabled: true
  kyverno:
    enabled: true
  external_secrets:
    enabled: true
  cni_metrics_helper:
    enabled: true
  cw_prometheus:
    enabled: true
  argocd:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-argocd ApplicationSet from the Hub Cluster
  external_secrets:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-external-secrets ApplicationSet the Hub Cluster
