name: frontend
labels:
  environment: staging
  app.kubernetes.io/created-by: eks-workshop
networkPolicies:
  enabled: true
  egress:
    deny:
      all:
        # -- create a NetworkPolicy that denies all outgoing traffic
        enabled: true
    allow:
      dns:
        # -- create a NetworkPolicy that allows outgoing traffic to the Kubernetes DNS
        enabled: true
        # -- The namespace where the Kubneretes DNS is running
        namespace: "kube-system"
  ingress:
    deny:
      all:
        # -- create a NetworkPolicy that denies all incoming traffic
        enabled: true
namespaces:
  assets:
    labels:
    limitRanges:
    - name: default
      limits:
        - defaultRequest: # this section defines default requests
            cpu: 500m
          #max: # max and min define the limit range
          #  cpu: "2" # MAx cpu is not recommended
          min:
            cpu: 100m
          type: Container
    resourceQuotas:
    - name: default
      spec:
        hard:
          cpu: "4"
          memory: 4Gi
          pods: "4"
    networkPolicies:
    - name: allow-ingress-from-ui
      spec:
        podSelector: {}
        policyTypes:
        - Ingress
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: ui
    roleBindings:
    - name: view
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: frontend-team-view

  ui:
    labels:
    limitRanges:
    - name: default
      limits:
        - defaultRequest: # this section defines default requests
            cpu: 500m
          #max: # max and min define the limit range
          #  cpu: "2" # MAx cpu is not recommended
          min:
            cpu: 100m
          type: Container
    resourceQuotas:
    - name: default
      spec:
        hard:
          cpu: "4"
          memory: 4Gi
          pods: "5"
    networkPolicies:
    - name: allow-ingress-from-vpc
      spec:
        podSelector: {}
        policyTypes:
        - Ingress
        ingress:
        - from:
          - ipBlock:
              cidr: 10.0.0.0/8
    - name: allow-egress-to-services
      spec:
        podSelector: {}
        policyTypes:
        - Egress
        egress:
        - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: assets
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: orders
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: checkout
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: carts
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: catalog
    roleBindings:
    - name: view
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: frontend-team-view
