{{- if .Values.gitSecrets.enabled }}
{{- $secretStoreRefName := .Values.gitSecrets.secretStoreRefName -}}
{{- $secretStoreRefKind := .Values.gitSecrets.secretStoreRefKind -}}
{{- $useHttp := .Values.gitSecrets.useHttp -}}
{{- range $externalSecretName, $externalSecret := .Values.gitSecrets.externalSecrets }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecretName }}
spec:
  secretStoreRef:
    kind: {{ $secretStoreRefKind }}
    name: {{ $secretStoreRefName }}
  refreshInterval: "1m"
  target:
    name: {{ $externalSecret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: repository"
      data:
        type: "git"
        url: "{{`{{ .url }}`}}"
        {{- if $useHttp }}
        username: "{{`{{ .username }}`}}"
        password: "{{`{{ .password }}`}}"
        {{- else }}
        insecureIgnoreHostKey: "true"
        sshPrivateKey: "{{`{{ .private_key }}`}}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ $externalSecret.secretManagerSecretName }}

---
{{- end }}
{{- end }}
